### ISSUE TITLE
Check out package.json and .gitignore file

### ISSUE THREAD

**Issue by jongfeel** [yoonucho/daily-report-project#1]
node_modules 폴더의 경우는 package 의존성에 의해 설치되는 걸로 알고 있어서 빼도 되는데...
이 node_mobules를 설치하는 package.json 파일 까지는 넣어 주셔야 나중에 npm update 시에 node_modules 폴더에 package 들이 설치가 됩니다.

react.js의 gitignore를 확인해 보셔서 올려야 되는 파일과 아닌 파일을 구분해서 올려 주시면 됩니다.
https://github.com/facebook/react/blob/master/.gitignore

정확히 말씀드리면 gitignore를 제외한 모든 파일을 github에 올려 주셔야 제가 확인이 가능하다는 얘기도 되지요.

요 부분도 확인 부탁드려요.

**Comment by yoonucho** [comment]
아하! 넵 빠른시일내로 올려두겠습니다!

**Comment by jongfeel** [comment]
잘 되네요!
