### ISSUE TITLE
제가 업데이트 예정인 내용에 대하여 이슈에 기록해둡니다.

### ISSUE THREAD

**Issue by yoonucho** [yoonucho/daily-report-project#14]
1. axios 와 fetch중 어떤걸 쓰는게 맞을지에 대해 알아보고 생각을 정리해 포스팅해보려고 합니다.

2. daily-report-project의   Class파일들을 Hook으로 리팩토링하려는 작업을 해보려고 합니다.

**Comment by jongfeel** [comment]
@yoonucho 
좋은 계획인 것 같습니다.

1번의 경우는 실제로 코드를 비교해 가면서 해보시면 좋을 것 같고, 특히 백엔드 쪽에서의 차이점도 생각해 보시면 좋습니다. fetch가 브라우저 api다 보니 node에서 돌리려면 node-fetch를 인스톨해야 하니 axios랑 또 차이가 없을 수도 있거든요.

2번의 경우는 리팩토링에만 집중해서 해보는걸 권장합니다. 대부분 리팩토링 + 기능 추가/구현/수정 을 같이 하긴 하는데, 리팩토링이라는 것을 왜 하는가에 초점을 맞추고 해보세요. (어려울 수 있지만 해 보면서 느낀점을 적는 정도만 해도 충분할 것 같네요)
