### ISSUE TITLE
이번주 업데이트 예정인 내용에 대하여 이슈에 기록해둡니다.

### ISSUE THREAD

**Issue by yoonucho** [yoonucho/daily-report-project#16]
우선 저번  [20190213 멘토링]( https://github.com/yoonucho/daily-report-project/blob/master/meeting/MeetingRecord%237_20190213.md)시간에 말씀하셨던 
WebServer와 ApplicationServer의 구분에 대해 검색은 해보았지만 아직 정리가 안되어서 정리 후 포스팅해보려고 합니다.

**Comment by jongfeel** [comment]
어렵게 생각하지 마시고 찾아보고 이해하는 식으로 해 보면 좋을 것 같습니다.

**Comment by yoonucho** [comment]
네네 그럴게요!

**Comment by yoonucho** [comment]
@jongfeel  멘토님 저번 [20190313 멘토링](https://github.com/yoonucho/daily-report-project/blob/master/meeting/MeetingRecord%2311_20190313.md) 시간에 
[되도록이면 서버, 클라이언트에서 type 변환을 하고 네트워크 상으로 주는 데이터는 encoding, byte array 형태로 주고 받는게 제일 안전하고 깔끔]하다고 하셨는데 byte array를 자바스크립트에서는 잘 사용을 안하는건지요? 검색해봤더니 파이썬,자바,스칼라 등은 나오는데 javascript는 잘 안나오고 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays#Examples 가 나오는데 솔직히 와닿지가 않아서요 ㅠㅠ

**Comment by jongfeel** [comment]
@yoonucho 
javascript는 잘 사용을 안하는게 아니고 다른 OS, platform 간의 protocol을 맞추는 작업 때문에 하는거라 이해하시면 되고, javascript library들이 그런 일들을 보이지 않게 해준다고 보시면 됩니다. 좀더 쉽게 설명하면 client-server 시스템간 통신은 표준적인 데이터 형태인 byte type으로 주고 받고 encoding (UTF-8, Unicode), string, json 변환은 이후에 작업하는 거죠.

사실 client가 webbrowser면 저절로 string type으로 주고 받을 수 있기 때문에
(물론 저절로 되는 것처럼 보이는 코드를 짜지만 이면에는 default encoding, byte array to string 변환 작업을 합니다)
client가 java나 C와 같이 byte 형태의 array를 전달하는 형태라면 서버도 그에 맞게 짜야 하기 때문에
모든 client 시스템을 맞추기 위한 서버는 encoding, byte array를 처리하는 형태로 하는게 맞다는 얘기입니다.

또 framework level이 아니라 OS level로 다른 거라면 big-endian, little-endian이냐에 따라서 byte array의 순서도 다르게 오는 것도 있습니다. 흔이 Unix <-> Windows에서 이런 일이 일어납니다.

이걸 이해하려면 client-server, network, endian, memory에 대한 기반 지식에 대한 이해가 필요하게 되는 거죠.

아래 링크의 질문과 답 역시 그런 일들을 직접 코드로 한다고 보시면 됩니다.
https://stackoverflow.com/questions/20979800/send-byte-array-in-node-js-to-server

javascript는 유독 type에 대한 개념이 강하지 않기 때문에 어렵다고 느낄 수 있지만,
우리가 아는 x86, x64 컴퓨터 시스템위에 도는 software는 다 똑같습니다.

**Comment by yoonucho** [comment]
친절하고 상세한 설명 감사드려요 링크 확인해보고 이해해보도록 하겠습니다!
