### ISSUE TITLE
 우선 server.js로 테스트해보려고  유닛테스트 찾아봤는데 솔직히 감이 잘안오네요 ㅠ 

### ISSUE THREAD

**Issue by yoonucho** [yoonucho/daily-report-project#4]

**Comment by jongfeel** [comment]
@yoonucho 
뭘 하던 처음엔 다 어렵죠.
unit test도 처음 접하면 그럴 겁니다.
어떤 감이 잘 안오셨는지에 대한 소감하고 어떤 어려움이 있었는지 정리해 보시면 좋을 것 같네요.

**Comment by yoonucho** [comment]
@jongfeel 
네 리뷰 써볼게요 감사합니다 ㅠㅠ

**Comment by yoonucho** [comment]
@jongfeel 
블로그에 포스팅해보았습니다 :smile_cat: 

[이슈노트6](https://yoonucho.github.io/issue_note/2019/01/16/unit_test1.html)
[unit test적용해보기](https://yoonucho.github.io/review/2019/01/16/unit_test2.html)
